import type { Metadata } from "next";
import { Arimo } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

const arimo = Arimo({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
	title: "Chris Ejik Group",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={arimo.className}>
				{children}
				<Footer />
			</body>
		</html>
	);
}
